### ISSUE TITLE
Publish deprecation notice

### ISSUE THREAD

**Issue by kevinburkeotto** [simonepri/tsse#1]
Node.js has a `timingSafeEqual` function built in as of version 6.6.0: https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b

It seems better to a) use that function if it's available and/or b) note in the README that people don't need to load a third party library to do that anymore.

**Comment by simonepri** [comment]
Hello @kevinburkeotto Thank You for the time you have spent opening this issue.

This package uses the builtin `timingSafeEqual` as you can see here:
https://github.com/simonepri/tsse/blob/master/index.js#L48

It uses the javascript implementation only if the node version is lower than the one you have specified.
It also adds the possibility to compare strings of different length (That is not possible by default with the builtin `timingSafeEqual`)
