### ISSUE TITLE
Leaking length info

### ISSUE THREAD

**Issue by LewisWolfgang** [simonepri/tsse#3]
I believe comparing the longest string to itself when the strings have different lengths can leak information about the length of a "secret" string when compared to a user-input string. So it would be safer to compare the "secret" string to itself in this case.

**Comment by simonepri** [comment]
Hi Lewis,
I think you are right!

Would you be able to submit a PR to fix this?

Thanks!

**Comment by simonepri** [comment]
Hi Lewis

I've added some code to check your claim and although I don't think that in practice we are actually leaking the length, the comparison time is not constant:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/3505087/172048055-792bd610-6638-401a-8d5b-e507dfa254a2.png">

So I decided to still apply your suggestion:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/3505087/172049182-9cbfc120-831c-4fa3-9167-1c0ee6ec9d46.png">

> avg = average
> md = median
